name: WarpDroid
version: ${project.version}
main: com.benjamintaillon.warpdroid.WarpDroid

commands:
    back:
        description: Teleports you to the location where you died.
        usage: /back
        permission: warpdroid.back
    call:
        description: Call one of your animals to you.
        usage: /call <petname>
        aliases: [callpet]
        permission: warpdroid.call
    callanimals:
        description: Teleports your tamed pets and animals to you.
        usage: /callanimals
        aliases: [callall]
        permission: warpdroid.call
    callpets:
        description: Teleports your pets back to you.
        usage: /callpets
        permission: warpdroid.call
    callhorses:
        description: Teleports your hores, mules and donkeys to you.
        usage: /callhorses
        aliases: [callmules, calldonkeys, callequines, callequidaes]
        permission: warpdroid.call
    calldogs:
        description: Teleports your dogs to you.
        usage: /calldogs
        aliases: [callwolves, callwolfs]
        permission: warpdroid.call
    callcats:
        Description: Teleports your cats to you.
        usage: /callcats
        aliases: [callocelots]
        permission: warpdroid.call
    callbirds:
        Description: Teleports your birds to you.
        usage: /callbirds
        permission: warpdroid.call
    home:
        description: Teleports you to your home warp.
        usage: /home
        aliases: [house]
        permission: warpdroid.home
    sethome:
        description: Move your home warp to your location.
        usage: /sethome
        aliases: [homeset, sethouse, houseset]
        permission: warpdroid.sethome
    warp:
        description: Warps to the specified warp. If no warp is given, calls the warplist command.
        usage: /warp <warpname>
        aliases: warps
        permission: warpdroid.warp
    warplist:
        description: Lists warps.
        usage: /warplist
        aliases: [listwarp, warpls, lswarp]
        permission: warpdroid.list
    addwarp:
        description: Creates a warp at your location.
        usage: /addwarp <warpname>
        aliases: [createwarp, addwarp, warpcreate, warpadd]
        permission: warpdroid.add
    setwarp:
        description: Move the specified warp to your location.
        usage: /setwarp <warpname>
        aliases: [warpset, movewarp, warpmove]
        permission: warpdroid.set
    removewarp:
        description: Removes a warp.
        usage: /removewarp <warpname>
        aliases: [warpremove, deletewarp, warpdelete, delwarp, warpdel, rmwarp, warprm]
        permission: warpdroid.remove
